micronaut:
  application:
    name: demo
  security:
    enabled: true
    intercept-url-map:
      - pattern: /hello
        http-method: GET
        access:
          - isAnonymous()
    authentication: session
    redirect:
      login-success: /
      login-failure: /login/authFailed
