name: Manually triggered workflow
on: workflow_dispatch
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello World!"
        ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1
