name: ZAP workflow
on: workflow_dispatch
    
jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.ref }}
          ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          
      - name: Run app
        run: |
            ./gradlew buildLayers
            ./gradlew dockerBuild
            docker-compose up -d
      - name: Stop app
        run: |
            docker-compose down
#       - name: ZAP Scan
#         uses: zaproxy/action-baseline@v0.4.0
#         with:
#           target: 'https://www.zaproxy.org'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
